### PR TITLE
Create default config

### LINKED ISSUE #41: add option to create default abaplint.json file from the extension
add option to create default abaplint.json file from the extension

### PR DESCRIPTION
**Pull request by g-back**
First draft, so it's a bit messy (but it works). Wanted to get some feedback before spending time cleaning up.
Thoughts? What should the naming for the action, request and response be?

Currently:

action: `abaplint.create.default-config`
request: `abaplint/config/default/request`
response: `abaplint/config/default/response`

resolves #41

### CODE REVIEW

**Comment by larshp** [comment]
looks good to me

**Comment by g-back** [comment]
Would you like to tackle #44 as well with this PR?
Workflow could be that the PR creator edits the changelog.md with [unreleased] as the version and you change it to the acutal version?

**Comment by larshp** [comment]
44: no, separate issue = separate PR (typically), try keeping the PRs small

**Comment by larshp** [comment]
how does this PR look from your side, is it okay to merge?

**Comment by g-back** [comment]
If you're fine with the naming, sure

**Pull request merged**
