### PR TITLE
Remote fs support

### PR DESCRIPTION
**Pull request by marcellourbani**
Ok Lars,
this is now working as far as I can tell, but has a few quirks:

- language server initialization happens after we told the client it was successful. As far as I understand this can't be helped (well, not without sending the initial config from the client)
- progress box for ls initialization doesn't work
- I took a shortcut or two in the server code I would like to clean up

Please don't merge until I fixed them, but this is close enough to what I plan to merge for an initial evaluation

On top of this, I would like to add a couple of features:
- abaplint config in vscode config files, to be used when no json file is provided (would require a lot of entries in package.json to support completion but still like it)
- multiple handlers with different configurations (mostly for the remote fs plugin: in the same system I can have n projects with independent abaplint.json files)

But I would rather put those in separate pull requests

### CODE REVIEW

**Comment by larshp** [comment]
👍 this is definitely the right direction

for merging, I'm okay with just the progress bar working

I have some comments regarding whitespace, but it should really be enforced by eslint, its just missing configuration there, it can be tackled later

**Comment by marcellourbani** [comment]
Before merging need to test this in windows and make sure the bloody \ works

**Comment by larshp** [comment]
Notes:
* forEach await async bug in addDependencies, changed to loop instead

**Comment by larshp** [comment]
@marcellourbani I've done a few changes, see above, I'll probably merge it now

**Comment by larshp** [comment]
0.4.91 published

**Pull request merged**
