### PR TITLE
Don't show button for xml files, remove dummy commands

### LINKED ISSUE #120: don't show abaplint button for xml files
Would it be okay to remove this part? I don't think it does anything for xml files.
```
{
  "when": "editorLangId == 'xml'",
  "command": "abaplint.show",
  "group": "navigation"
}
```

There are also two keyboard shortcuts registered which have no purpose.

### PR DESCRIPTION
**Pull request by FreHu**
resolves #120

### CODE REVIEW

**Comment by FreHu** [comment]
I also found xml in the client options, maybe it's also not necessary?
```ts
  const clientOptions: LanguageClientOptions = {
    documentSelector: [{language: "abap"}, {language: "xml"}],
    progressOnInitialization: true,
    initializationOptions:{
      provideFsProxy: true,
    },
    synchronize: {
      fileEvents: workspace.createFileSystemWatcher("**/abaplint.json*"),
    },
  };
```

**Comment by larshp** [comment]
I added these because I press it all the time, but looks like it has no effect, so lets try removing it 😄 

```
* Ctrl+F1 = do nothing
* Ctrl+F2 = do nothing
```

**Comment by larshp** [comment]
XML: please open as a separate issue?

**Comment by larshp** [comment]
0.4.310 published

**Pull request merged**
